site_name: "Bayesian Paired Samples"
site_url: "https://torodriguezt.github.io/BayesianPairedSamples/"
theme:
  name: "material"

nav:
  - Home: index.md
  - Functions:
      - densBB Function: docs/densBB.md
      - Error One Function: docs/error_one.md
      - Error Two Function: docs/error_two.md
      - Evidence Beta Function: docs/evidence_beta.md

use_directory_urls: false
