site_name: "Bayesian Paired Samples"
site_url: "https://torodriguezt.github.io/BayesianPairedSamples/"
theme:
  name: "material"

nav:
  - Home: index.md
  - Functions:
      - densBB Function: densBB.md
      - Error One Function: error_one.md
      - Error Two Function: error_two.md
      - Evidence Beta Function: evidence_beta.md

use_directory_urls: false
