site_name: "Bayesian Paired Samples"
theme:
  name: "material"

nav:
  - Home: index.md
  - Functions:
      - densBB: docs/densBB.md
      - Error One: docs/error_one.md
      - Error Two: docs/error_two.md
      - Evidence Beta: docs/evidence_beta.md
      - Full Evidence Beta: docs/full_evidence_beta.md
      - MC Integral Alpha: docs/mc_integral_alpha.md
      - Select K: docs/select_k.md
